#!/usr/bin/env python
# -*- coding: ascii -*-
import sys

"""
Algorithm to mine disjunctive frequent itemsets

  This algorithm differs from the conjunctive itemset mining algorithms
  in the sense that it mines ORed itemsets instead of ANDed itemsets.

  The algorithm makes use of FPTree to store the dataset in a condensed form.

  Steps carried out by this algorithms are as follows:
  (Step 1)   Read the original dataset and create a new dataset with items
          mapped to a unique integer i.e. map each item to a unique integer ID.
          This step will be termed as preprocessing.

  (Step 2)   Scan the new dataset and calculate the frequency of each item present
          in the dataset.

  (Step 3)    We scan the dataset one more time to build an FPTree using the
          the frequencies of the items

  (Step 4)    We next traverse the itemset lattice in the top down order i.e.
          enumerating the lattice from items with higher cardinality to items
          with less cardinality.

  (Step 5)    For each such itemset, check if the itemset is a subset of any
          maximal infrequent itemset:
          - if NO: Use the FP Tree Property to find the support of the itemset.

  (Step 6)    If the itemset has support value greater than the min support
          threshold, then we add the itemset to the frequent itemset list,
          along with its support value.

  (Step 7)    Step 4 to 6 are repeated for all itemsets in the itemset lattice.
          The algorithm stops when all itemsets have been processed. The resultant
          list of frequent itemsets form the list of disjunctive frequent itemsets
          generated by our algorithm.

"""

__author__ = 'Nihal Jain (nihal.jain@iitg.ernet.in)'
__version__ = '0.1'
__date__ = '20160810'

def processDataset(filePath, minSupp, numeric):
    """ Function to process the given dataset and generate a new dataset"""
    transactions = []

    # try to open the file and read its contents
    try:
        # prompt the user to enter the filepath of the given dataset
        # inputDatasetPath = input("Enter path to the input dataset: ")

        # fp is a file object used to operate on the file
        # we open the file in raed mode
        fp = open(filePath, "r")

        # reads the file until EOF using readline() and returns a list containing the lines
        # and stores it in variable lines
        lines = fp.readlines()

        # close the file after reading is complete
        fp.close()

    # raise exception and exit if there is any read error or if file is not found
    except IOError:
        print("ERROR: file not found or unable to read data")
        sys.exit(-1)

    for line in lines:
        if numeric:
            transaction = []
            for item in line.split():
                transaction.append(int(item))
            transactions.append(transaction)
        else:
            transactions.append(line.split())

    return transactions

if __name__ == '__main__':
    #main()

    from optparse import OptionParser

    opt = OptionParser(usage='%scriptName datasetPath')
    opt.add_option('-s','--minimum-support', dest='minSupp', type='int', help='Minimum itemset support (default = 2)')
    opt.add_option('-n', '--numeric', dest='numeric', action='store_true', help='Convert the values in the dataset to '
                                                                                'numerals (default = false)')
    opt.set_defaults(minSupp=2)
    opt.set_defaults(numeric=False)
    options, args = opt.parse_args()

    if len(args) < 1:
        opt.error('ERROR: Must provide the path to a dataset file')


    print('-------------------------------------------------------------------')
    print('     Disjunctive Frequent Itemset Mining: DFS Based Algorithm')
    print('-------------------------------------------------------------------')
    print('Parameters are as follows....')
    print('Dataset File Path: ' + str(args[0]))
    print('Minimum Support Threshold: ' + str(options.minSupp))
    print('-------------------------------------------------------------------')

    transactions = []
    transactions = processDataset(args[0], options.minSupp, options.numeric)

    for transaction in transactions:
        for item in transaction:
            print(str(item)+",")
        print('.\n')